// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package userpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_FoodPreferences int32

const (
	User_NONE        User_FoodPreferences = 0
	User_VEGAN       User_FoodPreferences = 1
	User_VEGETARIAN  User_FoodPreferences = 2
	User_PESCETARIAN User_FoodPreferences = 3
)

var User_FoodPreferences_name = map[int32]string{
	0: "NONE",
	1: "VEGAN",
	2: "VEGETARIAN",
	3: "PESCETARIAN",
}

var User_FoodPreferences_value = map[string]int32{
	"NONE":        0,
	"VEGAN":       1,
	"VEGETARIAN":  2,
	"PESCETARIAN": 3,
}

func (x User_FoodPreferences) String() string {
	return proto.EnumName(User_FoodPreferences_name, int32(x))
}

func (User_FoodPreferences) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1, 0}
}

type Location struct {
	Longitude            float64  `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type User struct {
	// The unique ID of the user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The user's first name
	FirstName int32 `protobuf:"varint,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// The user's last name
	LastName int32 `protobuf:"varint,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// The user's hashed and salted password
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// The user's location
	Location *Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// The user's allergens
	Allergens []string `protobuf:"bytes,6,rep,name=allergens,proto3" json:"allergens,omitempty"`
	// The user's food preferences
	// Note: front-end should provide drop-down component with ONLY these options
	FoodPreferences      User_FoodPreferences `protobuf:"varint,7,opt,name=food_preferences,json=foodPreferences,proto3,enum=io.homecook.service.user.User_FoodPreferences" json:"food_preferences,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() int32 {
	if m != nil {
		return m.FirstName
	}
	return 0
}

func (m *User) GetLastName() int32 {
	if m != nil {
		return m.LastName
	}
	return 0
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *User) GetAllergens() []string {
	if m != nil {
		return m.Allergens
	}
	return nil
}

func (m *User) GetFoodPreferences() User_FoodPreferences {
	if m != nil {
		return m.FoodPreferences
	}
	return User_NONE
}

type UserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("io.homecook.service.user.User_FoodPreferences", User_FoodPreferences_name, User_FoodPreferences_value)
	proto.RegisterType((*Location)(nil), "io.homecook.service.user.Location")
	proto.RegisterType((*User)(nil), "io.homecook.service.user.User")
	proto.RegisterType((*UserRequest)(nil), "io.homecook.service.user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "io.homecook.service.user.UserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4f, 0x8b, 0xd3, 0x40,
	0x14, 0x37, 0xe9, 0x9f, 0x4d, 0x5e, 0xb5, 0x2d, 0xa3, 0x87, 0x50, 0x57, 0x29, 0x01, 0xa5, 0x78,
	0x48, 0x30, 0xde, 0x3c, 0x08, 0xdd, 0x35, 0x16, 0x41, 0xe2, 0x32, 0xab, 0x0b, 0x7a, 0x59, 0x66,
	0x9b, 0xd7, 0x3a, 0x98, 0xe6, 0xc5, 0x99, 0xe9, 0x7a, 0x10, 0x2f, 0x7e, 0x05, 0x3f, 0x9a, 0x5f,
	0xc1, 0x0f, 0xe0, 0xc5, 0xbb, 0x64, 0x62, 0x5b, 0x14, 0xd6, 0x05, 0x61, 0x6f, 0x99, 0xdf, 0xef,
	0xfd, 0xfe, 0xbc, 0x21, 0x03, 0xb0, 0xd6, 0xa8, 0xa2, 0x4a, 0x91, 0x21, 0x16, 0x48, 0x8a, 0xde,
	0xd1, 0x0a, 0xe7, 0x44, 0xef, 0x23, 0x8d, 0xea, 0x5c, 0xce, 0x31, 0xaa, 0xf9, 0xd1, 0xfe, 0x92,
	0x68, 0x59, 0x60, 0x2c, 0x2a, 0x19, 0x8b, 0xb2, 0x24, 0x23, 0x8c, 0xa4, 0x52, 0x37, 0xba, 0xf0,
	0x29, 0x78, 0x2f, 0x68, 0x6e, 0x21, 0xb6, 0x0f, 0x7e, 0x41, 0xe5, 0x52, 0x9a, 0x75, 0x8e, 0x81,
	0x33, 0x76, 0x26, 0x0e, 0xdf, 0x01, 0x6c, 0x04, 0x5e, 0x21, 0x4c, 0x43, 0xba, 0x96, 0xdc, 0x9e,
	0xc3, 0x1f, 0x2e, 0xb4, 0x5f, 0x6b, 0x54, 0xac, 0x0f, 0xae, 0xcc, 0xad, 0xd6, 0xe7, 0xae, 0xcc,
	0xd9, 0x1d, 0x80, 0x85, 0x54, 0xda, 0x9c, 0x96, 0x62, 0xd5, 0xc8, 0x3a, 0xdc, 0xb7, 0x48, 0x26,
	0x56, 0xc8, 0x6e, 0x83, 0x5f, 0x88, 0x0d, 0xdb, 0xb2, 0xac, 0x57, 0x03, 0x96, 0x1c, 0x81, 0x57,
	0x09, 0xad, 0x3f, 0x92, 0xca, 0x83, 0xb6, 0x75, 0xdc, 0x9e, 0xd9, 0x13, 0xf0, 0x8a, 0xdf, 0xb5,
	0x83, 0xce, 0xd8, 0x99, 0xf4, 0x92, 0x30, 0xba, 0xe8, 0x06, 0xa2, 0xcd, 0x82, 0x7c, 0xab, 0xa9,
	0x57, 0x15, 0x45, 0x81, 0x6a, 0x89, 0xa5, 0x0e, 0xba, 0xe3, 0xd6, 0xc4, 0xe7, 0x3b, 0x80, 0xbd,
	0x81, 0xe1, 0x82, 0x28, 0x3f, 0xad, 0x14, 0x2e, 0x50, 0x61, 0x39, 0x47, 0x1d, 0xec, 0x8d, 0x9d,
	0x49, 0x3f, 0x89, 0x2e, 0x4e, 0xa9, 0xf7, 0x8f, 0x9e, 0x11, 0xe5, 0x47, 0x3b, 0x15, 0x1f, 0x2c,
	0xfe, 0x04, 0xc2, 0x19, 0x0c, 0xfe, 0x9a, 0x61, 0x1e, 0xb4, 0xb3, 0x97, 0x59, 0x3a, 0xbc, 0xc6,
	0x7c, 0xe8, 0x9c, 0xa4, 0xb3, 0x69, 0x36, 0x74, 0x58, 0x1f, 0xe0, 0x24, 0x9d, 0xa5, 0xaf, 0xa6,
	0xfc, 0xf9, 0x34, 0x1b, 0xba, 0x6c, 0x00, 0xbd, 0xa3, 0xf4, 0xf8, 0x70, 0x03, 0xb4, 0xc2, 0x29,
	0xf4, 0xea, 0x44, 0x8e, 0x1f, 0xd6, 0xa8, 0x0d, 0x4b, 0xa0, 0x5d, 0xb7, 0xb0, 0x57, 0xdf, 0x4b,
	0xee, 0xfe, 0xbb, 0x26, 0xb7, 0xb3, 0xe1, 0x01, 0x5c, 0x6f, 0x2c, 0x74, 0x45, 0xa5, 0xc6, 0xff,
	0xf1, 0x48, 0x7e, 0x3a, 0x4d, 0x8f, 0xe3, 0x86, 0x67, 0x15, 0xc0, 0xa1, 0x42, 0x61, 0xd0, 0xfe,
	0x0e, 0xf7, 0x2e, 0xf1, 0x68, 0xca, 0x8f, 0xee, 0x5f, 0x36, 0xd6, 0x14, 0x0c, 0x6f, 0x7e, 0xf9,
	0xf6, 0xfd, 0xab, 0x7b, 0x23, 0xf4, 0xe2, 0xf3, 0x87, 0x71, 0x4d, 0x3f, 0x76, 0x1e, 0x30, 0x03,
	0x7b, 0x33, 0x34, 0x57, 0x11, 0x37, 0xb2, 0x71, 0xb7, 0x18, 0xdb, 0xc4, 0xc5, 0x9f, 0xec, 0x90,
	0xcc, 0x3f, 0x1f, 0x78, 0x6f, 0xbb, 0xf5, 0x77, 0x75, 0x76, 0xd6, 0xb5, 0x0f, 0xe9, 0xd1, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0x05, 0x87, 0x7f, 0x8e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/io.homecook.service.user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/io.homecook.service.user.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *UserRequest) (*UserResponse, error)
	GetUser(context.Context, *UserRequest) (*UserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.homecook.service.user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.homecook.service.user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.homecook.service.user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
