apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/users/*
        backend:
          serviceName: homecook-users
          servicePort: 8080
      - path: /api/chefs/*
        backend:
          serviceName: homecook-chefs
          servicePort: 8081
