apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homecook-chefs
  name: homecook-chefs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homecook-chefs
  template:
    metadata:
      labels:
        app: homecook-chefs
    spec:
      containers:
        - name: homecook-chefs
          image: gcr.io/homecook/homecook-chefs:latest
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /chefs/v1/health
              port: 8081
          readinessProbe:
            httpGet:
              path: /chefs/v1/health
              port: 8081
      restartPolicy: Always
      imagePullSecrets:
        - name: gcrcred

---
apiVersion: v1
kind: Service
metadata:
  name: homecook-chefs
  labels:
    app: homecook-chefs
spec:
  selector:
    app: homecook-chefs
  ports:
    - port: 8081
  type: NodePort
