apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homecook-chefs
  name: homecook-chefs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homecook-chefs
  template:
    metadata:
      labels:
        app: homecook-chefs
    spec:
      containers:
      - name: homecook-chefs
        image: gcr.io/homecook/homecook-chefs:latest
        ports:
          - containerPort: 8081     
      livenessProbe:      # Used by deployment controller
        httpGet:
          path: /health
          port: 8081
        initialDelaySeconds: 3
        periodSeconds: 3 
      readinessProbe:    
        httpGet:
          path: /health
          port: 8081
        initialDelaySeconds: 3
        periodSeconds: 3
      restartPolicy: Always
      imagePullSecrets:
      - name: gcrcred
