apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homecook-users
  name: homecook-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homecook-users
  template:
    metadata:
      labels:
        app: homecook-users
    spec:
      containers:
      - name: homecook-users
        image: gcr.io/homecook/homecook-users:latest
        ports:
          - containerPort: 8080
      livenessProbe:      # Used by deployment controller
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3 
    readinessProbe:    
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
      restartPolicy: Always
      imagePullSecrets:
      - name: gcrcred
