// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chef.proto

package chefpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Location struct {
	Longitude            float64  `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e705f2f0ff9c45, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type Chef struct {
	// The unique ID of the chef
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The chef's first name
	FirstName int32 `protobuf:"varint,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// The chef's last name
	LastName int32 `protobuf:"varint,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// The chef's hashed and salted password
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// The chef's location
	Location *Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// The chef's rating
	Rating float32 `protobuf:"fixed32,6,opt,name=rating,proto3" json:"rating,omitempty"`
	// The number of ratings that the chef has gotten
	NumRating int32 `protobuf:"varint,7,opt,name=num_rating,json=numRating,proto3" json:"num_rating,omitempty"`
	// The recipes that the chef knows how to cook
	KnownRecipies        []string `protobuf:"bytes,8,rep,name=known_recipies,json=knownRecipies,proto3" json:"known_recipies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chef) Reset()         { *m = Chef{} }
func (m *Chef) String() string { return proto.CompactTextString(m) }
func (*Chef) ProtoMessage()    {}
func (*Chef) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e705f2f0ff9c45, []int{1}
}

func (m *Chef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chef.Unmarshal(m, b)
}
func (m *Chef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chef.Marshal(b, m, deterministic)
}
func (m *Chef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chef.Merge(m, src)
}
func (m *Chef) XXX_Size() int {
	return xxx_messageInfo_Chef.Size(m)
}
func (m *Chef) XXX_DiscardUnknown() {
	xxx_messageInfo_Chef.DiscardUnknown(m)
}

var xxx_messageInfo_Chef proto.InternalMessageInfo

func (m *Chef) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Chef) GetFirstName() int32 {
	if m != nil {
		return m.FirstName
	}
	return 0
}

func (m *Chef) GetLastName() int32 {
	if m != nil {
		return m.LastName
	}
	return 0
}

func (m *Chef) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Chef) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Chef) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Chef) GetNumRating() int32 {
	if m != nil {
		return m.NumRating
	}
	return 0
}

func (m *Chef) GetKnownRecipies() []string {
	if m != nil {
		return m.KnownRecipies
	}
	return nil
}

type ChefRequest struct {
	Chef                 *Chef    `protobuf:"bytes,1,opt,name=chef,proto3" json:"chef,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChefRequest) Reset()         { *m = ChefRequest{} }
func (m *ChefRequest) String() string { return proto.CompactTextString(m) }
func (*ChefRequest) ProtoMessage()    {}
func (*ChefRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e705f2f0ff9c45, []int{2}
}

func (m *ChefRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChefRequest.Unmarshal(m, b)
}
func (m *ChefRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChefRequest.Marshal(b, m, deterministic)
}
func (m *ChefRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChefRequest.Merge(m, src)
}
func (m *ChefRequest) XXX_Size() int {
	return xxx_messageInfo_ChefRequest.Size(m)
}
func (m *ChefRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChefRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChefRequest proto.InternalMessageInfo

func (m *ChefRequest) GetChef() *Chef {
	if m != nil {
		return m.Chef
	}
	return nil
}

type ChefResponse struct {
	Chef                 *Chef    `protobuf:"bytes,1,opt,name=chef,proto3" json:"chef,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChefResponse) Reset()         { *m = ChefResponse{} }
func (m *ChefResponse) String() string { return proto.CompactTextString(m) }
func (*ChefResponse) ProtoMessage()    {}
func (*ChefResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14e705f2f0ff9c45, []int{3}
}

func (m *ChefResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChefResponse.Unmarshal(m, b)
}
func (m *ChefResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChefResponse.Marshal(b, m, deterministic)
}
func (m *ChefResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChefResponse.Merge(m, src)
}
func (m *ChefResponse) XXX_Size() int {
	return xxx_messageInfo_ChefResponse.Size(m)
}
func (m *ChefResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChefResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChefResponse proto.InternalMessageInfo

func (m *ChefResponse) GetChef() *Chef {
	if m != nil {
		return m.Chef
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "io.homecook.service.chef.Location")
	proto.RegisterType((*Chef)(nil), "io.homecook.service.chef.Chef")
	proto.RegisterType((*ChefRequest)(nil), "io.homecook.service.chef.ChefRequest")
	proto.RegisterType((*ChefResponse)(nil), "io.homecook.service.chef.ChefResponse")
}

func init() { proto.RegisterFile("chef.proto", fileDescriptor_14e705f2f0ff9c45) }

var fileDescriptor_14e705f2f0ff9c45 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xb1, 0x6e, 0xd4, 0x40,
	0x10, 0x86, 0x65, 0xe7, 0xe2, 0xac, 0xe7, 0x48, 0x8a, 0x05, 0x21, 0xcb, 0x04, 0x64, 0x59, 0x0a,
	0xb2, 0x28, 0x6c, 0x61, 0x3a, 0x0a, 0x24, 0x12, 0x24, 0x1a, 0x44, 0xb1, 0x74, 0x34, 0xa7, 0x8d,
	0x3d, 0xe7, 0x5b, 0xc5, 0xde, 0x35, 0xde, 0x75, 0x52, 0x20, 0x1a, 0x6a, 0x3a, 0x1e, 0x8d, 0x57,
	0xe0, 0x15, 0xe8, 0x91, 0x77, 0x7d, 0x47, 0x75, 0x3a, 0x09, 0x29, 0x9d, 0xe7, 0xff, 0xe6, 0x9f,
	0xf9, 0x3d, 0x36, 0x40, 0xb5, 0xc1, 0x75, 0xde, 0x0f, 0xca, 0x28, 0x1a, 0x09, 0x95, 0x6f, 0x54,
	0x87, 0x95, 0x52, 0x37, 0xb9, 0xc6, 0xe1, 0x56, 0x54, 0x98, 0x4f, 0x3c, 0x3e, 0x6f, 0x94, 0x6a,
	0x5a, 0x2c, 0x78, 0x2f, 0x0a, 0x2e, 0xa5, 0x32, 0xdc, 0x08, 0x25, 0xb5, 0xf3, 0xa5, 0xef, 0x80,
	0x7c, 0x50, 0x95, 0x95, 0xe8, 0x39, 0x84, 0xad, 0x92, 0x8d, 0x30, 0x63, 0x8d, 0x91, 0x97, 0x78,
	0x99, 0xc7, 0xfe, 0x09, 0x34, 0x06, 0xd2, 0x72, 0xe3, 0xa0, 0x6f, 0xe1, 0xae, 0x4e, 0x7f, 0xf8,
	0xb0, 0xb8, 0xda, 0xe0, 0x9a, 0x9e, 0x81, 0x2f, 0x6a, 0xeb, 0x0d, 0x99, 0x2f, 0x6a, 0xfa, 0x14,
	0x60, 0x2d, 0x06, 0x6d, 0x56, 0x92, 0x77, 0xce, 0x76, 0xcc, 0x42, 0xab, 0x7c, 0xe4, 0x1d, 0xd2,
	0x27, 0x10, 0xb6, 0x7c, 0x4b, 0x8f, 0x2c, 0x25, 0x93, 0x60, 0x61, 0x0c, 0xa4, 0xe7, 0x5a, 0xdf,
	0xa9, 0xa1, 0x8e, 0x16, 0x76, 0xe2, 0xae, 0xa6, 0x6f, 0x80, 0xb4, 0x73, 0xec, 0xe8, 0x38, 0xf1,
	0xb2, 0x65, 0x99, 0xe6, 0xfb, 0x2e, 0x90, 0x6f, 0x5f, 0x90, 0xed, 0x3c, 0xf4, 0x31, 0x04, 0x03,
	0x37, 0x42, 0x36, 0x51, 0x90, 0x78, 0x99, 0xcf, 0xe6, 0x6a, 0xca, 0x2b, 0xc7, 0x6e, 0x35, 0xb3,
	0x13, 0x97, 0x57, 0x8e, 0x1d, 0x73, 0xf8, 0x02, 0xce, 0x6e, 0xa4, 0xba, 0x93, 0xab, 0x01, 0x2b,
	0xd1, 0x0b, 0xd4, 0x11, 0x49, 0x8e, 0xb2, 0x90, 0x9d, 0x5a, 0x95, 0xcd, 0x62, 0xfa, 0x16, 0x96,
	0xd3, 0x35, 0x18, 0x7e, 0x19, 0x51, 0x1b, 0x5a, 0xc2, 0x62, 0xca, 0x61, 0xcf, 0xb2, 0x2c, 0x9f,
	0xed, 0x0f, 0x6a, 0x4d, 0xb6, 0x37, 0xbd, 0x84, 0x07, 0x6e, 0x84, 0xee, 0x95, 0xd4, 0xf8, 0x3f,
	0x33, 0xca, 0x3f, 0x9e, 0xcb, 0xf1, 0xc9, 0x71, 0xda, 0x03, 0x5c, 0x0d, 0xc8, 0x0d, 0xda, 0x4f,
	0x75, 0x71, 0x60, 0x86, 0x0b, 0x1f, 0x3f, 0x3f, 0xd4, 0xe6, 0x02, 0xa6, 0x0f, 0xbf, 0xff, 0xfa,
	0xfd, 0xd3, 0x3f, 0x4d, 0x49, 0x71, 0xfb, 0xb2, 0x98, 0xf0, 0x6b, 0xef, 0x05, 0x35, 0x70, 0xf2,
	0x1e, 0xcd, 0x7d, 0xac, 0x8b, 0xed, 0xba, 0x47, 0x94, 0x6e, 0xd7, 0x15, 0x5f, 0x6d, 0x93, 0xa8,
	0xbf, 0x5d, 0x92, 0xcf, 0xc1, 0xf4, 0xdc, 0x5f, 0x5f, 0x07, 0xf6, 0x27, 0x7f, 0xf5, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xac, 0x0d, 0x2f, 0xd3, 0x2a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChefServiceClient is the client API for ChefService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChefServiceClient interface {
	CreateChef(ctx context.Context, in *ChefRequest, opts ...grpc.CallOption) (*ChefResponse, error)
	GetChef(ctx context.Context, in *ChefRequest, opts ...grpc.CallOption) (*ChefResponse, error)
}

type chefServiceClient struct {
	cc *grpc.ClientConn
}

func NewChefServiceClient(cc *grpc.ClientConn) ChefServiceClient {
	return &chefServiceClient{cc}
}

func (c *chefServiceClient) CreateChef(ctx context.Context, in *ChefRequest, opts ...grpc.CallOption) (*ChefResponse, error) {
	out := new(ChefResponse)
	err := c.cc.Invoke(ctx, "/io.homecook.service.chef.ChefService/CreateChef", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chefServiceClient) GetChef(ctx context.Context, in *ChefRequest, opts ...grpc.CallOption) (*ChefResponse, error) {
	out := new(ChefResponse)
	err := c.cc.Invoke(ctx, "/io.homecook.service.chef.ChefService/GetChef", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChefServiceServer is the server API for ChefService service.
type ChefServiceServer interface {
	CreateChef(context.Context, *ChefRequest) (*ChefResponse, error)
	GetChef(context.Context, *ChefRequest) (*ChefResponse, error)
}

func RegisterChefServiceServer(s *grpc.Server, srv ChefServiceServer) {
	s.RegisterService(&_ChefService_serviceDesc, srv)
}

func _ChefService_CreateChef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChefServiceServer).CreateChef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.homecook.service.chef.ChefService/CreateChef",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChefServiceServer).CreateChef(ctx, req.(*ChefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChefService_GetChef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChefServiceServer).GetChef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.homecook.service.chef.ChefService/GetChef",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChefServiceServer).GetChef(ctx, req.(*ChefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChefService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.homecook.service.chef.ChefService",
	HandlerType: (*ChefServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChef",
			Handler:    _ChefService_CreateChef_Handler,
		},
		{
			MethodName: "GetChef",
			Handler:    _ChefService_GetChef_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chef.proto",
}
